name: Request Form
description: Suggest an idea for this project
title: Give me a good name
labels: ["enhancement", "help wanted"]
assignees: "ErickOF"
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us to resolve your request.
  -type: dropdown
    id: language
    attributes:
      label: Select the programming language
      multiple: true
      options:
        - Python
        - Octave
    validations:
      required: true
  -type: dropdown
    id: method
    attributes:
      label: Select the method type
      multiple: true
      options:
        - One Variable Equations
        - Systems of Equations
        - Function Approximation
        - Numerical Integration
        - Ordinary Differential Equation
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the algorithm steps
      placeholder: Describe the algorithm steps, paste a link to a web page or video.
    validations:
      required: true
  - type: textarea
    id: inputs
    attributes:
      label: Input values
      placeholder: List each input and describe what they are for
      validations:
        required: true
  - type: textarea
    id: behaviour
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen.
      validations:
        required: true
  - type: textarea
    id: tests
    attributes:
      label: Tests
      placeholder: Add at least 3 examples to test the algorithm.
      validation:
        required: true
  - type: markdown
    attributes:
      value: |
        Thank you for your request! We will reach you as soon as possible.
