name: Formulario para peticiones
description: Sugierí una idea para este proyecto
title: Dame un buen nombre
labels: ["enhancement", "help wanted"]
assignees: "ErickOF"
body:
- type: markdown
  attributes:
    value: |
      Por favor llenar las secciones abajo para ayudarnos a resolver tu petición.
- type: dropdown
  id: language
  attributes:
    label: Seleccionar el lenguaje de programación
    multiple: true
    options:
      - Python
      - Octave
  validations:
    required: true
- type: dropdown
  id: method
  attributes:
    label: Seleccionar el tipo de método
    multiple: true
    options:
      - Ecuaciones de una variable
      - Sistemas de ecuaciones
      - Aproximación de funciones
      - Integración numérica
      - Ecuaciones diferenciales ordinarias
      - Otro
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Descripción de los pasos del algoritmo
    placeholder: Descripción de los pasos del algoritmo, enlace a alguna página web y video de YouTube.
  validations:
    required: true
- type: textarea
  id: steps
  attributes:
    label: Valores de entrada.
    placeholder: Lista de cada entrada y la descripción de para qué es cada una.
  validations:
    required: true
- type: textarea
  id: behaviour
  attributes:
    label: Comportamiento esperado
    placeholder: Descripción clara y concisa de qué se espera que pase.
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Pruebas
    placeholder: Agregar al menos tres ejemplos para probar el algoritmo.
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      ¡Gracias por la petición! Te contactaremos tan pronto como sea posible.
